### PR TITLE
Rich Sentry events - no breadcrumbs

### PR DESCRIPTION
**Pull request by ramirogm**

### CODE REVIEW

**Comment by ramirogm** [comment]
Build is failing because

```
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/logwatcher - You do not have permission to publish "logwatcher". Are you logged in as the correct user?
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
```

**Comment by joshbwlng** [comment]
@ramirogm Yeah, that was my bad, a name I went with when this repo was under my personal account and I wasn't publishing anything to npmjs. Updating the package name in https://github.com/balenablocks/logwatcher/pull/22 so this should be resolved before too long. 👍

**Comment by ramirogm** [comment]
@balena-ci retest

**Comment by joshbwlng** [comment]
@ramirogm I'm fine with you self certifying this once everything works the way you expect. 👍 We don't have much time left and I don't want the time zone difference to be a blocker to you making progress.

**Comment by ramirogm** [comment]
@balena-ci I self-certify!

**Pull request merged**
